# Generated by Django 6.1.1 on 2026-10-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhãn hàng')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Tồn kho')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('specs', models.TextField(blank=True, verbose_name='Thông số')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
